package com.dpx.tracker.enums;

public enum Industry {
    TECHNOLOGY,
    FINANCE,
    HEALTHCARE,
    EDUCATION,
    MANUFACTURING,
    RETAIL,
    TRANSPORTATION,
    ENERGY,
    REAL_ESTATE,
    ENTERTAINMENT,
    TELECOMMUNICATIONS,
    AGRICULTURE,
    CONSTRUCTION,
    HOSPITALITY,
    PROFESSIONAL_SERVICES,
    GOVERNMENT,
    NON_PROFIT
}
